// import "../../../node_modules/react-modal-video/css/modal-video.css"
import "./public/assets/css/bootstrap.css"
import "./public/assets/css/style.css"
import "./public/assets/css/responsive.css"
import "./public/assets/css/color.css"
import "./main.css"
import 'swiper/css'
import "swiper/css/pagination"
import 'swiper/css/free-mode';
import { inter, jost } from './lib/font'
export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={`${inter.variable} ${jost.variable}`}>
            <body>{children}</body>
        </html>
    )
}